config/routes.rb
Rails.application.routes.draw do
	
	
	
	
  post 'twilio/sms'
	authenticated :user,    lambda { |u| u.yonetici?|| u.ogretmen? } do
		resources :ogrencis,  :except => [:show]
		resources :ogretmen
		resources :devamsizliks
		resources :odevs, :except =>[:index,:show]

	end

	authenticated :user,    lambda { |u| u.ogrenci?|| u.ogretmen? || u.yonetici? } do
		resources :odevs, :only =>[:index,:show]

	end

	resources :ogrencis, only:[:show]



	devise_for :users, :controllers => { :registrations => 'registrations' } 
	authenticated :user, lambda {|u| u.yonetici?} do
		resources :users, except: :create, except: :compose
		post 'create_user' => 'users#create', as: :create_user 
		post 'compose_user' => 'users#compose', as: :compose_user  
		get '/new2/user', action: :new2, controller: 'users'
		post '/users/:id/edit', to: 'users#update'
		patch '/users/:id/edit', to: 'users#update'
		resources :sinifs
	end


	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/odev.rb
class Odev < ApplicationRecord

	def self.to_csv(options = {})
		desired_columns = ["id","ad","soyad","sinif","ders_adi","date","teslim_date"]
		CSV.generate(options) do |csv|
			csv << desired_columns
			all.each do |odev|
				csv << odev.attributes.values_at(*desired_columns)
			end
		end
	end
end

app/controllers/odevs_controller.rb
class OdevsController < ApplicationController
  
  before_action :set_odev, only: [:show, :edit, :update, :destroy]

  # GET /odevs
  # GET /odevs.json
  def index
   @search=Odev.ransack(params[:q])
   @odevs=@search.result.all.order("created_at DESC")

   respond_to do |format|
    format.html
    format.csv { send_data @odevs.to_csv }
    format.xls  
  end


end

  # GET /odevs/1
  # GET /odevs/1.json
  def show
  end

  # GET /odevs/new
  def new
    @odev = Odev.new
  end

  # GET /odevs/1/edit
  def edit
  end

  # POST /odevs
  # POST /odevs.json
  def create
    @odev = Odev.new(odev_params)
    @odev.date=Date.today
    

    respond_to do |format|
      if @odev.save
        format.html { redirect_to @odev, notice: 'Odev was successfully created.' }
        format.json { render :show, status: :created, location: @odev }
      else
        format.html { render :new }
        format.json { render json: @odev.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /odevs/1
  # PATCH/PUT /odevs/1.json
  def update
    respond_to do |format|
      if @odev.update(odev_params)
        format.html { redirect_to @odev, notice: 'Odev was successfully updated.' }
        format.json { render :show, status: :ok, location: @odev }
      else
        format.html { render :edit }
        format.json { render json: @odev.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /odevs/1
  # DELETE /odevs/1.json
  def destroy
    @odev.destroy
    respond_to do |format|
      format.html { redirect_to odevs_url, notice: 'Odev was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_odev
      @odev = Odev.find(params[:id])
      @ogrenci=Ogrenci.find(@odev.ogrid)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def odev_params
      params.require(:odev).permit(:ogrid, :ogretmen_id, :ad, :soyad, :sinif, :date, :teslim_date, :ders_adi, :aciklama, :durum)
    end
  end

app/helpers/odevs_helper.rb
module OdevsHelper
end

app/views/odevs/_form.html.erb
<div class="wrapper ">
  <%= render 'shared/sidebar'%>
  <div class="main-panel">
    <%= render 'shared/navbar'%>
    <div class="content">
      <%= form_with(model: odev, local: true) do |form| %>

      <% if odev.errors.any? %>
      <div id="error_explanation">
        <h2> <div class="alert alert-primary">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="material-icons">close</i>
          </button>
          <span>
            <b> Mesaj: </b> <%= pluralize(odev.errors.count, "error") %> </span>
          </div>prohibited this ogrenci from being saved:</h2>


        </div>
        <% end %>
        <body>

          <div class="container-fluid">
            <div class="row">
              <div class="col-md-2"></div>

              <div class="col-md-8">




                <% if flash[:notice] %>
                <div class="alert alert-warning">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="material-icons">close</i>
                  </button>
                  <span><%= flash[:notice] %>
                  </span>
                </div>
                <% end %>

                <% if odev.ogrid.blank? %>
                <% ogrid = params[:id] %>
                <% else %>
                <% ogrid = odev.ogrid  %>
                <% end %>

                <div class="card">
                  <div class="card-header card-header-primary">
                    <h4 class="card-title">Ödev Kayıt</h4>
                    <p class="card-category">Öğrenci Ödev Kayıt Formu</p>
                  </div>
                  <div class="card-body">
                    <form>
                      <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                            <label class="bmd-label-floating">Adı</label>
                            <%= form.text_field :ad , :value=> Ogrenci.find_by(ogrid).adi, class: "form-control"%>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <label class="bmd-label-floating">Soyadı</label>
                            <%= form.text_field :soyad , :value=> Ogrenci.find_by(ogrid).soyadi, class: "form-control"%>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          <div class="form-group">
                            <label class="bmd-label-floating">Ogrenci No:</label>
                            <%= form.text_field :ogrid , :value=> Ogrenci.find_by(ogrid).id, class: "disable form-control"%>                            
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="form-group">
                            <label class="bmd-label-floating">Sınıfı</label>
                            <%= form.text_field :sinif , :value=> Ogrenci.find_by(ogrid).sinif, class: "form-control"%>                            
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="form-group">
                            <label class="">Teslim Tarihi</label>
                            <%= form.date_field :teslim_date,class: "form-control" %>                           
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <label class="bmd-label-floating">Dersin Adı</label>
                            <%= form.text_field :ders_adi,class: "form-control" %>                         
                          </div>
                        </div>
                      </div>                 

                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label class="bmd-label-floating">Ödev Açıklaması(İçeriği)</label>
                            <%= form.text_area :aciklama,class: "form-control" %>                           
                          </div>
                        </div>
                      </div>



                      <%= link_to 'Back', :back, class: "btn btn-primary pull-left" %>
                      <button type="submit" name="commit" class="btn btn-primary pull-right">Kaydet</button>
                      <div class="clearfix"></div>
                    </form>
                  </div>
                </div>
              </div>
              <div class="col-md-2"></div>
            </div>
          </div>

        </div>
        <%= render 'shared/footer'%>
      </div>
    </div>
  </body>


  <% end %>

app/views/odevs/edit.html.erb
<h1>Editing Odev</h1>

<%= render 'form', odev: @odev %>

<%= link_to 'Show', @odev %> |
<%= link_to 'Back', odevs_path %>

app/views/odevs/index.html.erb
<style type="text/css">
.fa-eye{

}
</style>
<body>
  <div class="wrapper ">
    <%= render 'shared/sidebar'%>
    <div class="main-panel">
      <%= render 'shared/navbar'%>
      <div class="content">
       <p id="notice"><%= notice %></p>



       
       <div class="container-fluid">

        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-warning">
              <h2 class="card-title">Öğrenciler</h2>
              <h4 class="card-category">Öğrenci Bilgileri</h4>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <div class="row" style="padding-left: 50px;">
                  <%=search_form_for @search do |f| %>
                  
                  <label class="">TC NO</label>
                  <%= f.text_field :ogrid_cont%>
                  
                  
                  <label class="">Başlangıç Tarih</label>
                  <%=f.date_field :date_gteq%>
                  
                  
                  <label class="">Son Tarih</label>
                  <%=f.date_field :date_lteq%>

                  <label class="">TC NO</label>
                  <%= f.collection_select :sinif_cont,Sinif.select(:adi),:adi,:adi%>
                  
                  <br>
                  <%=f.submit "Arama Yap", class: "btn btn-primary pull-right" %>
                  <%= link_to "CSV", odevs_path(format: "csv"), class: "btn btn-warning pull-right" %> 
                  <%= link_to 'Export', 
                  odevs_path(request.parameters.merge({format: :xls})), 
                  download: 'Öğrenciler.xls', class: "btn btn-warning pull-right" %>
                  
                  <%end%>
                </div>
                <table class="table">
                  <thead>
                    <tr>
                      <th>Adi</th>
                      <th>Soyadi</th>
                      <th>Sınıfı</th>
                      <th>Ödev Aldığı Ders</th>
                      <th>Ödev Verilen Tarih</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @odevs.each do |odev| %>
                    <tr>
                      <td><%= odev.ad %></td>
                      <td><%= odev.soyad %></td>
                      <td><%= odev.sinif %></td>
                      <td><%= odev.ders_adi %></td>
                      <td><%= odev.date.strftime("%d-%m-%Y")%></td>
                      <td><%= link_to '', odev, class: "btn btn-primary fa fa-eye", style:"font-size:1em;" %></td>
                      <td><%= link_to '', edit_odev_path(odev), class: "btn btn-primary fa fa-edit", style: "font-size: 1em" %></td>
                      <td><%= link_to '', odev, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary fa fa-trash-alt", style:"font-size:1em;"  %></td>
                      <td> <%= link_to 'Yeni Kullanıcı Olustur', new_user_path , class: "btn btn-primary " %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <%= render 'shared/footer'%>
  </div>
</div>
</body>

app/views/odevs/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Öğrenciler">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Adı</Data></Cell>
        <Cell><Data ss:Type="String">Soyadı</Data></Cell>
        <Cell><Data ss:Type="String">Sınıf</Data></Cell>
        <Cell><Data ss:Type="String">Ders Adı</Data></Cell>
        <Cell><Data ss:Type="String">Verildiği Tarih</Data></Cell>
        <Cell><Data ss:Type="String">Teslim Tarihi</Data></Cell>


      </Row>
      <% @odevs.each do |odevs| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= odev.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= odev.ad %></Data></Cell>
        <Cell><Data ss:Type="String"><%= odev.soyad %></Data></Cell>
        <Cell><Data ss:Type="String"><%= odev.sinif %></Data></Cell>
        <Cell><Data ss:Type="String"><%= odev.ders_adi %></Data></Cell>
        <Cell><Data ss:Type="String"><%= odev.date %></Data></Cell>
        <Cell><Data ss:Type="String"><%= odev.teslim_date %></Data></Cell>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/odevs/new.html.erb
<h1>New Odev</h1>

<%= render 'form', odev: @odev %>

<%= link_to 'Back', odevs_path %>

app/views/odevs/show.html.erb
 <style type="text/css">
 .bmd-label-floating{
  font-size: 16px;
  color: black;
}
</style>
<body>
  <div class="wrapper ">
    <%= render 'shared/sidebar'%>
    <div class="main-panel">
      <%= render 'shared/navbar'%>

      <div class="content">

        <div class="container-fluid">
         <div class="row">

          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Öğrenci Bilgileri</h4>

              </div>
              <div class="card-body">
                <form>
                  <div class="row">
                    <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                     <%= image_tag @ogrenci.avatar.url,class: "img-thumbnail", style:"margin-left:40px; width:200px; height:200px;" %>
                   </div>

                   <div class="col-md-8">
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Adı: </label>
                          <label class="bmd-label-floating"><%= @odev.ad %>
                          </label>

                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Soyadı: </label>
                          <label class="bmd-label-floating"><%= @odev.soyad %>
                          </label>

                        </div>
                      </div>
                    </div>
                    <br>


                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Ogrenci No: </label>
                          <label class="bmd-label-floating"><%= @odev.ogrid %></label>

                        </div>
                      </div>

                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Sınıfı: </label>
                          <label class="bmd-label-floating"><%= @odev.sinif %></label>

                        </div>
                      </div>

                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Ders:</label>
                          <label class="bmd-label-floating"><%= @odev.ders_adi %></label>

                        </div>
                      </div>
                    </div>
                  </div>



                </div>

                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="bmd-label-floating">Ödevin Verildiği Tarih: </label>
                      <label class="bmd-label-floating"><%= @odev.date %>
                      </label>

                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="bmd-label-floating">Ödev Teslim Tarihi: </label>
                      <label class="bmd-label-floating"><%= @odev.teslim_date %>
                      </label>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label class="bmd-label-floating">Ödev Açıklaması: </label>
                      <label class="bmd-label-floating"><%= @odev.aciklama %>
                      </label>
                    </div>
                  </div>
                </div>

                  <%if current_user.yonetici?%>
                  <%= link_to 'Hesap oluştur', new_user_path(:ogrid => @ogrenci.id), class: "btn btn-primary" %>
                  <%= link_to 'Devamsızlık İşle', new_devamsizlik_path(:tc_no => @ogrenci.id), class: "btn btn-primary" %> 
                  <%= link_to 'Ödev Oluştur', new_odev_path(:ogrid => @ogrenci.id), class: "btn btn-primary" %> 
                  <%= link_to 'Edit', edit_ogrenci_path(@ogrenci), class: "btn btn-primary" %> 
                  <%= link_to 'Back', ogrencis_path, class: "btn btn-primary" %>
                  <%end%>
                  <div class="clearfix"></div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <%= render 'shared/footer'%>
      </div>
    </div>
  </body>