config/routes.rb
Rails.application.routes.draw do
	
	
	
	
  post 'twilio/sms'
	authenticated :user,    lambda { |u| u.yonetici?|| u.ogretmen? } do
		resources :ogrencis,  :except => [:show]
		resources :ogretmen
		resources :devamsizliks
		resources :odevs, :except =>[:index,:show]

	end

	authenticated :user,    lambda { |u| u.ogrenci?|| u.ogretmen? || u.yonetici? } do
		resources :odevs, :only =>[:index,:show]

	end

	resources :ogrencis, only:[:show]



	devise_for :users, :controllers => { :registrations => 'registrations' } 
	authenticated :user, lambda {|u| u.yonetici?} do
		resources :users, except: :create, except: :compose
		post 'create_user' => 'users#create', as: :create_user 
		post 'compose_user' => 'users#compose', as: :compose_user  
		get '/new2/user', action: :new2, controller: 'users'
		post '/users/:id/edit', to: 'users#update'
		patch '/users/:id/edit', to: 'users#update'
		resources :sinifs
	end


	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:ogrenci, :ogretmen, :yonetici] # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  
  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  attr_writer :login

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login
    @login || self.username || self.email
  end

 # def soft_delete  
  #  update_attribute(:is_deleted, true)  
  #end  
  
  # ensure user account is active  
  #def active_for_authentication?  
   # super && !is_deleted  
  #end  
  
  # provide a custom message for a deleted account   
  #def inactive_message   
   # !is_deleted ? super : :deleted_account  
  #end  

  #def self.search(keywords)
   # user = order(:created_at)
    #user = User.where("username like ? OR email like ?", "%#{keywords}%","%#{keywords}%") if keywords.present?
    #user
  #end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :authorize_admin, only: :create
	before_action :set_user, only: [:edit, :update]

	def index
		@users=User.all.order("created_at DESC")
	end
	
	def new 
		@user=User.new
	end

	def new2 
		@user=User.new
	end

	def edit
	end

	def create
		@user=User.new(user_params)

		if User.exists?(username:  @user.username)
			flash[:notice] = "Bu kullanıcı zaten KAYITLI !!"
			redirect_to :back
		else
			if current_user.yonetici?
				if @user.save
					flash[:notice]="Kullanıcı hesabı oluşturuldu. !!"
					redirect_to users_path
				end
			else
				flash[:notice]="Kullanıcı hesabını sadece yönetici oluşturabilir."
				redirect_to new_user_path

			end
		end
	end

	def compose
		@user=User.new(user_params)

		if User.exists?(username:  @user.username)
			flash[:notice] = "Bu kullanıcı zaten KAYITLI !!"
			redirect_to :back
		else
			if current_user.yonetici?
				if @user.save
					flash[:notice]="Kullanıcı hesabı oluşturuldu. !!"
					redirect_to users_path
				end
			else
				flash[:notice]="Kullanıcı hesabını sadece yönetici oluşturabilir."
				redirect_to new_user_path

			end
		end
	end


	def update

		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to users_path, notice: 'Kullanıcı Güncellendi!' }
				format.json { render :show, status: :ok, location: @user}
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end


	private
	def set_user
		@user=User.find(params[:id])
	end
	def authorize_admin
		return unless !current_user.yonetici?
		redirect_to root_path, alert: 'Admins only!'
	end
	def user_params
		params.require(:user).permit(:ogrid, :role, :username, :email, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body>
	<div class="wrapper ">
		<%= render 'shared/sidebar'%>
		<div class="main-panel">
			<%= render 'shared/navbar'%>
			<div class="content">
				<%= form_for @user, url: edit_user_path do |f| %>
				<% if flash[:notice] %>
				<div class="notice"><%= flash[:notice] %>
				</div>
				<% end %>
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-4"></div>

						<div class="col-md-4" >
							<div class="card">
								<div class="card-header card-header-primary">
									<h4 class="card-title">Güncelleme Formu</h4>
									<p class="card-category">Kullanıcı Hesabı Güncelleme Formu</p>
								</div>
								<div class="card-body">
									<form>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Kullanıcı Adı</label>
													<%= f.text_field :username, class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Mail Adresi</label>
													<%= f.email_field :email, autofocus: true, class: "form-control", autocomplete: "email" %>
												</div>
											</div>
										</div>



										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Yetki Kontrolü: </label>
													<%= f.select :role, [['Öğrenci',"ogrenci"], ['Öğretmen',"ogretmen"], ['Yönetici',"yonetici"]] ,class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Şifre</label>
													<% if @minimum_password_length %>
													<% end %>
													<%= f.password_field :password, autocomplete: "off",class: "form-control" %>
													<em>(<%= @minimum_password_length %> characters minimum)</em>
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Tekrar Şifre</label>
													<%= f.password_field :password_confirmation, autocomplete: "off",class: "form-control" %>
												</div>
											</div>
										</div>

										<%= f.submit "Kaydet", class: "btn btn-primary pull-right btn-block" %> <br>
										<%= render "devise/shared/links" %>
										<div class="clearfix"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-md-4"></div>
					</div>
				</div>

				<%end%>
			</div>
			<%= render 'shared/footer'%>
		</div>
	</div>
</body>

app/views/users/index.html.erb
<body>
	<div class="wrapper ">
		<%= render 'shared/sidebar'%>
		<div class="main-panel">
			<%= render 'shared/navbar'%>
			<div class="content">

				<div class="container-fluid">

					<div class="col-md-12">
						<div class="card">
							<div class="card-header card-header-primary">
								<h4 class="card-title ">Öğrenciler</h4>
								<p class="card-category">Öğrenci Bilgileri</p>
							</div>
							<div class="card-body">
								<div class="table-responsive">

									<table class="table">
										<thead>
											<tr>
												<th>Kullanıcı Adı</th>
												<th>Email</th>
												<th>Hesabın Oluşturulma Tarihi</th>
												<th>Son Girdiği IP</th>
												<th>Kullanıcı Rolü</th>
												<th>Kullanıcı Hesap Ayarları</th>


											</tr>

										</thead>
										<tbody>
											<% @users.each do |user| %>
											<tr data-expanded="true">
												<td><%= user.username %></td>
												<td><%= user.email %></td>
												<td><%= user.role %></td>
												<td><%= user.created_at.strftime("%d-%m-%Y") %></td>
												<td><%=user.last_sign_in_ip%></td>


												<td class="text-center"> <%= link_to '', edit_user_path(user) , class:"btn btn-warning fa fa-edit " , style:"font-size:1em;"%></td>

											</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
			<%= render 'shared/footer'%>
		</div>
	</div>
</body>

app/views/users/new.html.erb
<body>
	<div class="wrapper ">
		<%= render 'shared/sidebar'%>
		<div class="main-panel">
			<%= render 'shared/navbar'%>
			<div class="content">
				<%= form_for User.new, url: create_user_path do |f| %>
				<% if flash[:notice] %>
				<div class="notice"><%= flash[:notice] %>
				</div>
				<% end %>

				<% ogrid = params[:ogrid] %>
				
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-4"></div>

						<div class="col-md-4">
							<div class="card">
								<div class="card-header card-header-primary">
									<h4 class="card-title">Kayıt Formu</h4>
									<p class="card-category">Kullanıcı Hesabı Oluşturma Formu</p>
								</div>
								<div class="card-body">
									<form>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Öğrenci İd si</label>
													<%= f.text_field :ogrid , :value=> Ogrenci.find_by(ogrid).id, class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Kullanıcı Adı</label>
													<%= f.text_field :username, class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Mail Adresi</label>
													<%= f.email_field :email, autofocus: true, class: "form-control", autocomplete: "email" %>
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Yetki Kontrolü: </label>
													<%= f.select :role, [['Öğrenci',"ogrenci"], ['Öğretmen',"ogretmen"], ['Yönetici',"yonetici"]] ,class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Şifre</label>
													<% if @minimum_password_length %>
													<% end %>
													<%= f.password_field :password, autocomplete: "off",class: "form-control" %>
													<em>(<%= @minimum_password_length %> characters minimum)</em>
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Tekrar Şifre</label>
													<%= f.password_field :password_confirmation, autocomplete: "off",class: "form-control" %>
												</div>
											</div>
										</div>

										<%= f.submit "Kaydet", class: "btn btn-primary pull-right btn-block" %> <br>
										<%= render "devise/shared/links" %>
										<div class="clearfix"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-md-4"></div>
					</div>
				</div>
				
				<%end%>

			</div>
			<%= render 'shared/footer'%>
		</div>
	</div>
</body>

app/views/users/new2.html.erb
<body>
	<div class="wrapper ">
		<%= render 'shared/sidebar'%>
		<div class="main-panel">
			<%= render 'shared/navbar'%>
			<div class="content">
				<%= form_for User.new, url: compose_user_path do |f| %>
				<% if flash[:notice] %>
				<div class="notice"><%= flash[:notice] %>
				</div>
				<% end %>

				<% ogrid = params[:ogrid] %>
				
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-4"></div>

						<div class="col-md-4">
							<div class="card">
								<div class="card-header card-header-primary">
									<h4 class="card-title">Kayıt Formu</h4>
									<p class="card-category">Kullanıcı Hesabı Oluşturma Formu</p>
								</div>
								<div class="card-body">
									<form>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Öğrenci İd si</label>
													<%= f.text_field :ogrid , :value=> Ogrenci.find_by(ogrid).id, class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Kullanıcı Adı</label>
													<%= f.text_field :username, class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Mail Adresi</label>
													<%= f.email_field :email, autofocus: true, class: "form-control", autocomplete: "email" %>
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Yetki Kontrolü: </label>
													<%= f.select :role, [['Öğrenci',"ogrenci"], ['Öğretmen',"ogretmen"], ['Yönetici',"yonetici"]] ,class: "form-control" %>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Şifre</label>
													<% if @minimum_password_length %>
													<% end %>
													<%= f.password_field :password, autocomplete: "off",class: "form-control" %>
													<em>(<%= @minimum_password_length %> characters minimum)</em>
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label class="bmd-label-floating">Tekrar Şifre</label>
													<%= f.password_field :password_confirmation, autocomplete: "off",class: "form-control" %>
												</div>
											</div>
										</div>

										<%= f.submit "Kaydet", class: "btn btn-primary pull-right btn-block" %> <br>
										<%= render "devise/shared/links" %>
										<div class="clearfix"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-md-4"></div>
					</div>
				</div>
				
				<%end%>

			</div>
			<%= render 'shared/footer'%>
		</div>
	</div>
</body>