config/routes.rb
Rails.application.routes.draw do
	
	
	
	
  post 'twilio/sms'
	authenticated :user,    lambda { |u| u.yonetici?|| u.ogretmen? } do
		resources :ogrencis,  :except => [:show]
		resources :ogretmen
		resources :devamsizliks
		resources :odevs, :except =>[:index,:show]

	end

	authenticated :user,    lambda { |u| u.ogrenci?|| u.ogretmen? || u.yonetici? } do
		resources :odevs, :only =>[:index,:show]

	end

	resources :ogrencis, only:[:show]



	devise_for :users, :controllers => { :registrations => 'registrations' } 
	authenticated :user, lambda {|u| u.yonetici?} do
		resources :users, except: :create, except: :compose
		post 'create_user' => 'users#create', as: :create_user 
		post 'compose_user' => 'users#compose', as: :compose_user  
		get '/new2/user', action: :new2, controller: 'users'
		post '/users/:id/edit', to: 'users#update'
		patch '/users/:id/edit', to: 'users#update'
		resources :sinifs
	end


	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
 <footer class="footer">
  <div class="container-fluid">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.creative-tim.com">
            Bera Ar-Ge & Yazılım & Danışmanlık 
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
      &copy;
      2018  made with <i class="material-icons">favorite</i> by
      <a href="#" target="_blank">Bera Ar-Ge & Yazılım & Danışmanlık </a> for a better web.
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
   <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
    <div class="container-fluid">
      <div class="navbar-wrapper">

      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
      </button>
    </div>
  </nav>

app/views/shared/_sidebar.html.erb
 <div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
      -->
      <div class="logo">
        <a href="<%=root_path%>" class="simple-text logo-normal">
          DERSHANEM
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">

          
          <%if current_user.ogretmen? %>

          <li class="nav-item">
            <a class="nav-link" href="<%=ogretman_path(current_user.ogrid)%>">
              <i class="material-icons">person_pin</i>
              <p>Profilim</p>
            </a>
          </li>

          <%end%>

          <%if current_user.ogrenci?%>
          <li class="nav-item">
            <a class="nav-link" href="<%=ogrenci_path(current_user.ogrid)%>">
              <i class="material-icons">school</i>
              <p>Profilim</p>
            </a>
          </li>          
          <%end%>

          <% if user_signed_in? %>
          <%if current_user.yonetici?%>
          <li class="nav-item">
            <a class="nav-link" href="<%= edit_user_path(current_user)%>">
              <i class="material-icons">settings</i>
              <p>Hesap Ayarları</p>
            </a>
          </li>
          <%end%>
          <li class="nav-item ">
            <a class="nav-link" href="<%=destroy_user_session_path%>"  data-method="delete">
              <i class="material-icons">forward</i>
              <p>Çıkış</p>
            </a>
          </li>
          <% else %>

          <li class="nav-item ">
            <a class="nav-link" href="<%=new_user_session_path%>">
              <i class="material-icons">forward</i>
              <p>Giriş</p>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=new_user_registration_path%>">
              <i class="material-icons">person_pin</i>
              <p>Kayıt Ol</p>
            </a>
          </li>

          <%end%>



          <%if current_user.yonetici?%>

          <li class="nav-item">
            <a class="nav-link" href="<%=new_ogrenci_path%>">
              <i class="material-icons">school</i>
              <p>Öğrenci Kayıt</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=ogrencis_path%>">
              <i class="material-icons">school</i>
              <p>Öğrenciler</p>
            </a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="<%=devamsizliks_path%>">
              <i class="material-icons">school</i>
              <p>Öğrenci Devamsızlıkları</p>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=new_ogretman_path%>">
              <i class="material-icons">school</i>
              <p>Öğretmen Kayıt</p>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=ogretmen_path%>">
              <i class="material-icons">school</i>
              <p>Öğretmenler</p>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="<%=users_path%>">
              <i class="material-icons">person</i>
              <p>Kullanıcılar</p>
            </a>
          </li>
          
          <%elsif current_user.ogretmen?%>
          
          <li class="nav-item">
            <a class="nav-link" href="<%=new_ogrenci_path%>">
              <i class="material-icons">school</i>
              <p>Öğrenci Kayıt</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=ogrencis_path%>">
              <i class="material-icons">school</i>
              <p>Öğrenciler</p>
            </a>
          </li>
          <%end%>


        </ul>
      </div>
    </div>