config/routes.rb
Rails.application.routes.draw do
	
	
	
	
  post 'twilio/sms'
	authenticated :user,    lambda { |u| u.yonetici?|| u.ogretmen? } do
		resources :ogrencis,  :except => [:show]
		resources :ogretmen
		resources :devamsizliks
		resources :odevs, :except =>[:index,:show]

	end

	authenticated :user,    lambda { |u| u.ogrenci?|| u.ogretmen? || u.yonetici? } do
		resources :odevs, :only =>[:index,:show]

	end

	resources :ogrencis, only:[:show]



	devise_for :users, :controllers => { :registrations => 'registrations' } 
	authenticated :user, lambda {|u| u.yonetici?} do
		resources :users, except: :create, except: :compose
		post 'create_user' => 'users#create', as: :create_user 
		post 'compose_user' => 'users#compose', as: :compose_user  
		get '/new2/user', action: :new2, controller: 'users'
		post '/users/:id/edit', to: 'users#update'
		patch '/users/:id/edit', to: 'users#update'
		resources :sinifs
	end


	root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/devamsizlik.rb
class Devamsizlik < ApplicationRecord
	after_create :notify_subscribers

	def notify_subscribers
		client = Twilio::REST::Client.new
		ad=Devamsizlik.last.ad
		soyad=Devamsizlik.last.soyad
		devamsizlik=Devamsizlik.last.devamsizlik_miktari
		tarih=Devamsizlik.last.created_at.strftime("%d-%m-%Y")
		
		client.messages.create(
			from: "+13344588041",
			to: Devamsizlik.last.mesaj_tel,
			body: "Velisi olduğunuz " + ad + soyad + " isimli öğrencinin dershanemizde" + tarih + " tarihinde " + devamsizlik + " miktarinda devamsızlığı olmuştur. Bilginize."
			)
		
	end
end

app/controllers/devamsizliks_controller.rb
class DevamsizliksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_devamsizlik, only: [:show, :edit, :update, :destroy]

  # GET /devamsizliks
  # GET /devamsizliks.json
  def index
    @search=Devamsizlik.ransack(params[:q])
   @devamsizliks=@search.result.all.order("created_at DESC")
 end

  # GET /devamsizliks/1
  # GET /devamsizliks/1.json
  def show
  end

  # GET /devamsizliks/new
  def new
    @devamsizlik = Devamsizlik.new
  end

  # GET /devamsizliks/1/edit
  def edit
  end

  # POST /devamsizliks
  # POST /devamsizliks.json
  def create
    @devamsizlik = Devamsizlik.new(devamsizlik_params)

    respond_to do |format|
      if @devamsizlik.save
        format.html { redirect_to @devamsizlik, notice: 'Devamsizlik was successfully created.' }
        format.json { render :show, status: :created, location: @devamsizlik }
      else
        format.html { render :new }
        format.json { render json: @devamsizlik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devamsizliks/1
  # PATCH/PUT /devamsizliks/1.json
  def update
    respond_to do |format|
      if @devamsizlik.update(devamsizlik_params)
        format.html { redirect_to @devamsizlik, notice: 'Devamsizlik was successfully updated.' }
        format.json { render :show, status: :ok, location: @devamsizlik }
      else
        format.html { render :edit }
        format.json { render json: @devamsizlik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devamsizliks/1
  # DELETE /devamsizliks/1.json
  def destroy
    @devamsizlik.destroy
    respond_to do |format|
      format.html { redirect_to devamsizliks_url, notice: 'Devamsizlik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devamsizlik
      @devamsizlik = Devamsizlik.find(params[:id])
      @ogrenci=Ogrenci.find(@devamsizlik.tc_no)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def devamsizlik_params
      params.require(:devamsizlik).permit(:ad, :soyad, :tc_no, :mesaj_tel, :ogrsinif, :devamsizlik_miktari)
    end
  end

app/helpers/devamsizliks_helper.rb
module DevamsizliksHelper
end

app/views/devamsizliks/_form.html.erb
 <div class="wrapper ">
  <%= render 'shared/sidebar'%>
  <div class="main-panel">
    <%= render 'shared/navbar'%>
    <div class="content">
      <%= form_with(model: devamsizlik, local: true) do |form| %>
      <% if devamsizlik.errors.any? %>
      <div id="error_explanation">
        <h2> <div class="alert alert-primary">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="material-icons">close</i>
          </button>
          <span>
            <b> Mesaj: </b> <%= pluralize(devamsizlik.errors.count, "error") %> </span>
          </div>prohibited this ogrenci from being saved:</h2>


          <ul>
            <% devamsizlik.errors.full_messages.each do |message| %>


            <div class="alert alert-primary">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <i class="material-icons">close</i>
              </button>
              <span>
                <b> Mesaj: </b> <%= message %></span>
              </div>
              <% end %>
            </ul>
          </div>
          <% end %>
          <% if devamsizlik.tc_no.blank? %>
          <% ogrid = params[:tc_no] %>
          <% else %>
          <% ogrid = devamsizlik.tc_no  %>
          <% end %>

          <body>

            <div class="container-fluid">
              <div class="row">
                <div class="col-md-2"></div>

                <div class="col-md-8">
                  <div class="card">
                    <div class="card-header card-header-primary">
                      <h4 class="card-title">Öğrenci Devamsızlık Kayıt</h4>
                      <p class="card-category">Öğrenci Devamsızlık Kayıt Formu</p>
                    </div>
                    <div class="card-body">
                      <form>
                       <form>
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="bmd-label-floating">Adı</label>
                              <%= form.text_field :ad , :value=> Ogrenci.find_by(ogrid).adi, class: "form-control"%>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="bmd-label-floating">Soyadı</label>
                              <%= form.text_field :soyad , :value=> Ogrenci.find_by(ogrid).soyadi, class: "form-control" %>

                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="bmd-label-floating">TC Kimlik Numarası</label>
                              <%= form.text_field :tc_no , :value=> Ogrenci.find_by(ogrid).id, class: "form-control" %>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="bmd-label-floating">Veli Telefonu</label>
                              <%= form.text_field :mesaj_tel , :value=> Ogrenci.find_by(ogrid).veli_tel, class: "form-control" %>                            
                            </div>
                          </div>


                        </div>



                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="bmd-label-floating">Devamsızlık Miktarı</label>
                              <%= form.select :devamsizlik_miktari, [['Yarım Gün',"Yarım Gün"],['Tam Gün',"Tam Gün"]], class: "form-control" %>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label class="bmd-label-floating">Sınıfı</label>
                              <%= form.collection_select :ogrsinif, Sinif.select(:adi),:adi,:adi, class: "form-control"%>
                            </div>
                          </div>
                        </div>

                        <%= link_to 'Back', :back, class: "btn btn-primary pull-left" %>
                        <button type="submit" name="commit" class="btn btn-primary pull-right">Kaydet</button>
                        <div class="clearfix"></div>
                      </form>
                    </div>
                  </div>
                </div>
                <div class="col-md-2"></div>
              </div>
            </div>

          </div>
          <%= render 'shared/footer'%>
        </div>
      </div>
    </body>


    <% end %>




    <%= form_with(model: devamsizlik, local: true) do |form| %>
    <% if devamsizlik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(devamsizlik.errors.count, "error") %> prohibited this devamsizlik from being saved:</h2>

      <ul>
        <% devamsizlik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= form.label :ad %>
      <%= form.text_field :ad %>
    </div>

    <div class="field">
      <%= form.label :soyad %>
      <%= form.text_field :soyad %>
    </div>

    <div class="field">
      <%= form.label :tc_no %>
      <%= form.text_field :tc_no %>
    </div>

    <div class="field">
      <%= form.label :mesaj_tel %>
      <%= form.text_field :mesaj_tel %>
    </div>

    <div class="field">
      <%= form.label :ogrsinif %>
      <%= form.text_field :ogrsinif %>
    </div>

    <div class="field">
      <%= form.label :devamsizlik_miktari %>
      <%= form.text_field :devamsizlik_miktari %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>

app/views/devamsizliks/edit.html.erb
<h1>Editing Devamsizlik</h1>

<%= render 'form', devamsizlik: @devamsizlik %>

<%= link_to 'Show', @devamsizlik %> |
<%= link_to 'Back', devamsizliks_path %>

app/views/devamsizliks/index.html.erb
<style type="text/css">
.fa-eye{

}
</style>
<body>
  <div class="wrapper ">
    <%= render 'shared/sidebar'%>
    <div class="main-panel">
      <%= render 'shared/navbar'%>
      <div class="content">
       <p id="notice"><%= notice %></p>



       
       <div class="container-fluid">

        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-warning">
              <h2 class="card-title">Devamsızlıklar</h2>
              <h4 class="card-category">Öğrenci Devamsızlık Bilgileri</h4>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <div class="row" style="padding-left: 50px;">
                  <%=search_form_for @search do |f| %>
                  
                  <label class="">TC NO</label>
                  <%= f.text_field :tc_no_cont%>
                  
                  
                  <label class="">Başlangıç Tarih</label>
                  <%=f.date_field :created_at_gteq%>
                  
                  
                  <label class="">Son Tarih</label>
                  <%=f.date_field :created_at_lteq%>
                  
                  <%=f.submit "Arama Yap", class: "btn btn-primary" %>
                  <%end%>
                  
                </div>
                <table class="table">
                 <thead>
                  <tr>
                    <th>Ad</th>
                    <th>Soyad</th>
                    <th class="text-center">Ogrenci No</th>
                    <th>Mesaj tel</th>
                    <th>Ogrsinif</th>
                    <th class="text-center">Devamsizlik miktari</th>
                    <th class="text-center">Devamsızlık Tarihi</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @devamsizliks.each do |devamsizlik| %>
                  <tr>
                   <td><%= devamsizlik.ad %></td>
                   <td><%= devamsizlik.soyad %></td>
                   <td><%= devamsizlik.tc_no %></td>
                   <td><%= devamsizlik.mesaj_tel %></td>
                   <td><%= devamsizlik.ogrsinif %></td>
                   <td><%= devamsizlik.devamsizlik_miktari %></td>
                   <td><%= devamsizlik.created_at.strftime("%d-%m-%Y")%></td>
                   <td><%= link_to '', devamsizlik, class: "btn btn-primary fa fa-eye", style:"font-size:1em;" %></td>
                   <td><%= link_to '', edit_devamsizlik_path(devamsizlik), class: "btn btn-primary fa fa-edit", style: "font-size: 1em" %></td>
                   <td><%= link_to '', devamsizlik, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary fa fa-trash-alt", style:"font-size:1em;"  %></td>

                 </tr>
                 <% end %>
               </tbody>
             </table>
           </div>
         </div>
       </div>
     </div>
   </div>

 </div>
 <%= render 'shared/footer'%>
</div>
</div>
</body>

app/views/devamsizliks/new.html.erb
<%= render 'form', devamsizlik: @devamsizlik %>

app/views/devamsizliks/show.html.erb
<style type="text/css">
.bmd-label-floating{
  font-size: 16px;
  color: black;
}
</style>
<body>
  <div class="wrapper ">
    <%= render 'shared/sidebar'%>
    <div class="main-panel">
      <%= render 'shared/navbar'%>

      <div class="content">

        <div class="container-fluid">
         <div class="row">

          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Öğrenci Bilgileri</h4>

              </div>
              <div class="card-body">
                <form>
                  <div class="row">
                    <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                     <%= image_tag @ogrenci.avatar.url,class: "img-thumbnail", style:"margin-left:40px; width:200px; height:200px;" %>
                   </div>

                   <div class="col-md-8">
                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Adı: </label>
                          <label class="bmd-label-floating"><%= @devamsizlik.ad %>
                          </label>

                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Soyadı: </label>
                          <label class="bmd-label-floating"><%= @devamsizlik.soyad %>
                          </label>

                        </div>
                      </div>
                    </div>
                    <br>


                    <div class="row">
                      <div class="col-md-5">
                        <div class="form-group">
                          <label class="bmd-label-floating">Tel No : </label>
                          <label class="bmd-label-floating"><%= @devamsizlik.mesaj_tel %></label>

                        </div>
                      </div>

                      <div class="col-md-4">
                        <div class="form-group">
                          <label class="bmd-label-floating">Devamsızlık Miktarı: </label>
                          <label class="bmd-label-floating"><%= @devamsizlik.devamsizlik_miktari %></label>

                        </div>
                      </div>

                      <div class="col-md-3">
                        <div class="form-group">
                          <label class="bmd-label-floating">Tarih:</label>
                          <label class="bmd-label-floating"><%= @devamsizlik.created_at.strftime("%d-%m-%Y")%></label>

                        </div>
                      </div>
                    </div>
                  </div>



                </div>



                <%if current_user.yonetici?%>

                <%= link_to 'Edit', edit_devamsizlik_path(@devamsizlik) , class: "btn btn-primary"%> 
                <%= link_to 'Back', devamsizliks_path, class: "btn btn-primary" %>

                <%end%>
                <div class="clearfix"></div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <%= render 'shared/footer'%>
    </div>
  </div>
</body>